import sys
list_names = ['Kira',
              'Mireya',
              'Julie',
              'Brynlee',
              'Haleigh',
              'Lailah',
              'Tara',
              'Marianna',
              'Makayla',
              'Jaidyn',
              'Kyla',
              'Aniya',
              'Alyson',
              'Ryann',
              'Kiley',
              'Maddison',
              'Livia',
              'Reese',
              'Cindy',
              'Leila']
tuple_names = ('Kira',
               'Mireya',
               'Julie',
               'Brynlee',
               'Haleigh',
               'Lailah',
               'Tara',
               'Marianna',
               'Makayla',
               'Jaidyn',
               'Kyla',
               'Aniya',
               'Alyson',
               'Ryann',
               'Kiley',
               'Maddison',
               'Livia',
               'Reese',
               'Cindy',
               'Leila')

print("list_size", sys.getsizeof(list_names))
print("tuple_size", sys.getsizeof(tuple_names))
